# Generated by Django 3.2.9 on 2021-11-28 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='User',
        ),
    ]
